# Generated by Django 2.2.4 on 2020-02-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Usuarios', '0003_auto_20200207_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente_transito',
            name='fotoA',
            field=models.FileField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
